Install CLR palette on MacOS #28
verocloud/color-sorting-cli pull request #77
Opened 2023-03-22 06:08 UTC by nguyenhieu123

Copy .clr file to Color folder in macos.

2023-03-22 06:15 UTC, AdrianSimionov commented
Can you please describe in words the functionality you are adding? Also, make sure the added functionality is documented in  the README file.

2023-03-22 06:17 UTC, nguyenhieu123 commented
Yes, I will add it

2023-03-22 09:09 UTC, AdrianSimionov commented
What I meant by describing in words, is to describe the functionality in plain English, as below:

Does this change break the previous functionality where a CLR file was created locally? Does it change it? How is changed?
Does this change add an argument so that when the argument is used, the file is also copied to the MacOS Library folder?
If such an argument is present, is the behavior described properly in the documentation?

2023-03-22 15:31 UTC, xlurio requested changes
Please, also review the name of your branch. We shall use the git flow naming conventions (https://dev.to/couchcamote/git-branching-name-convention-cch).

2023-03-22 15:31 UTC, xlurio commented on harmony/to_clr_convertion/commands.py
> +    _copy_file_macos(file_path_clr)
This line is breaking the functionality of the command. This command is only for converting "Harmony" files into `.clr` files. "Installing" `.clr` should be placed in a new command. The new command should also raise an Exception in case the file is not a `.clr` file (doesn't have the `04 0b 73 74 72 65 61 6d 74 79 70 65 64` signature byte string at the beginning of the file) or the current OS is not MacOS, since this functionality is exclusive to Apple operating systems

2023-03-22 23:53 UTC, xlurio commented on harmony/to_clr_convertion/commands.py
> +    _copy_file_macos(file_path_clr)
In respect to https://github.com/verocloud/color-sorting-cli/issues/28#issuecomment-1480297615, instead of creating a new command we will add a new flag option (which value will be `False` by default). The option must have a OS checking which will raise an error in case it is used in a OS different from MacOS.

2023-03-23 01:48 UTC, nguyenhieu123 commented
Yes, I understand, I will fixed it.

2023-03-23 13:45 UTC, nguyenhieu123 commented on harmony/to_clr_convertion/commands.py
> +    _copy_file_macos(file_path_clr)
Hello xlurio, Do we need created the new flag? I think we can checking os in command logic, if it is macos then i will copy file to Colors library and if not, We run command normally.

2023-03-26 09:05 UTC, AdrianSimionov commented
Please add changes here.

2023-03-26 09:52 UTC, nguyenhieu123 commented
> Please add changes here.

I created new branch. Can I created merge branch to this branch.

2023-03-26 10:36 UTC, nguyenhieu123 commented
This Pull Request:

1. Copy .clr file to Color folder in macos.
2. Add function "copy_file_macos" , "checking_os", "check_os_and_copy_file" in "hamony/to_clr_convertion/utils"
3. Add new flag "--mac_os" default is False in "txt2clr" command
4. Add test for write .clr file for macos

The problem of issue is that when running the command to create .clr file, the file is created in the project's folder, the user has to move the file to the Colors folder of macos. The idea is that when running command create the .clr file, I make a copy and move it to the Colors folder of macos. I add the new flag "--macos" in command write .clr file to run function copy file to Colors folder if it's os is macos .

2023-03-27 14:28 UTC, xlurio requested changes

2023-03-27 14:28 UTC, xlurio commented on tests/writing_strategies_tests/test_clr_writing.py
> +    def test_write_as_clr_file_with_macos(self, monkeypatch) -> None:
In Harmony API, every entity should have its own test module, and you are using the module that tests the `CLRWriting` class to test other entity. Please, follow the pattern and write your tests in a separated module.
For the file you gonna use for the test, you can convert a Harmony file into a `.clr` file and place it into `tests/resources` folder. Then you copy the file into a [temporary directory](https://docs.python.org/3.8/library/tempfile.html#tempfile.TemporaryDirectory) and work the test from there.
Also, please [setup a Docker container](https://dockerlabs.collabnix.com/beginners/dockerfile/lab_dockerfile_python.html) for the tests, I don't think nobody wants to have a test messing around with them OSs everytime the tests are runned. Stay free for calling for help, I know Docker documentation is not one of the best.

2023-03-30 01:25 UTC, nguyenhieu123 commented on harmony/commands.py
> -        suffix: str,
Since the lint test raise "too many argument in function", I add the the new argument in kwags.

2023-03-30 07:41 UTC, nguyenhieu123 commented on harmony/to_clr_convertion/utils.py
> +def copy_file_macos(file_path_clr) -> None:
Since the lint test raise "too many argument in function", I add the the new argument in kwags. When i get argument keywords, i set it default value

2023-03-30 07:48 UTC, nguyenhieu123 commented on harmony/to_clr_convertion/utils.py
> +def copy_file_macos(file_path_clr) -> None:
I will put two function in class but when i put it into term service, lint's checking raise line is too long, the number of line in service is limited

2023-03-30 13:46 UTC, nguyenhieu123 commented on tests/writing_strategies_tests/test_clr_writing.py
> +    def test_write_as_clr_file_with_macos(self, monkeypatch) -> None:
Can you guide me or give document to package test documentation into docker file.

2023-03-31 02:39 UTC, xlurio commented on harmony/commands.py
> -        suffix: str,
You can disable this error for `__init__` methods. Do like this:
```
def __init__( # pylint: disable=too-many-arguments
        ...
):
    ...
```

Some classes may have a lot of attributes and, because of that, `__init__` may have a lot of arguments. Other functions and methods should have no more than three arguments.

2023-03-31 02:52 UTC, xlurio commented on harmony/commands.py
> +        self.__mac_os = bool(kwargs.get("mac_os", False))
As I already mentioned in the other comment, the `too-many-arguments` can be ignored for `__init__` method.
As for the default value you could do just `kwargs["mac_os"]` since a case where the `__init__` does not receive this argument is a programming error.

2023-03-31 02:58 UTC, xlurio commented on harmony/to_clr_convertion/utils.py
> +def copy_file_macos(file_path_clr) -> None:
You can create a new module called `io_services` or something, just don't use the term `utils` unless it attends the said terms.

2023-03-31 03:02 UTC, xlurio commented on tests/writing_strategies_tests/test_clr_writing.py
> +    def test_write_as_clr_file_with_macos(self, monkeypatch) -> None:
Well there is the [official documentation](https://docs.docker.com/language/python/build-images/), but I think it's easier for us to build it together. Be in Discord tomorrow at 14:00 UTC and we will work on it.

2023-03-31 06:35 UTC, nguyenhieu123 commented on harmony/commands.py
> -        suffix: str,
thank you, I will follow it

2023-03-31 06:38 UTC, nguyenhieu123 commented on tests/writing_strategies_tests/test_clr_writing.py
> +    def test_write_as_clr_file_with_macos(self, monkeypatch) -> None:
Great, See you at 14:00 UTC

2023-04-01 04:42 UTC, nguyenhieu123 commented
The pull request:

1. Change the tag from --macos to --install.
2. Claim the copy_file and check_os function to class and change it to "io_service.py".
3. Write the docker file for test, and change the test for copy file function.
4. Remove "kwangs" in argument of some function

2023-04-04 23:17 UTC, xlurio commented on harmony/core/__init__.py
> +    Txt2ClrArguments,
the `core` module is only for the **shared API**, `Txt2ClrArguments` is only used into `to_clr_convertion` thus it should be in `to_clr_convernio.constants`

2023-04-04 23:18 UTC, xlurio commented on harmony/core/constants.py
> +class Txt2ClrArguments:
https://github.com/verocloud/color-sorting-cli/pull/77/files#r1157855573

2023-04-04 23:46 UTC, xlurio requested changes
Just a few changes left!

2023-04-04 23:53 UTC, xlurio commented on harmony/core/constants.py
> +        help="Save the file .clr to Colors folder in macos",
Please change the description to `"Store the '.clr' as a color palette in MacOS"` and take care with upper and lower cases as this text will be showed to the user.

2023-04-05 00:01 UTC, xlurio commented on harmony/to_clr_convertion/utils.py
> +def copy_file_macos(file_path_clr) -> None:
Item **2** is still pending

2023-04-05 00:07 UTC, xlurio commented on harmony/to_clr_convertion/io_services.py
> +            rich.print("[green]File is copied to Colors folder successfully!")
Please, avoid outputting messages outside commands. Add a new attribute to the class which will become `True` in case the `.clr` file was installed as a color palette and move the `rich.print()` line to the command.

2023-04-05 00:08 UTC, xlurio commented on harmony/commands.py
> +        utils.check_os_and_copy_file(self.__mac_os, file_path_str)
Item **2** still pending

2023-04-26 01:40 UTC, closed without merging