Build/full poetry
verocloud/color-sorting-cli pull request #85
Opened 2023-04-18 03:10 UTC by RomuloGatto

Closes #78 

This pull request:
1. Add the shortcut for linting on demand `make lint`
2. Remove the requirements and use poetry directly on the CI/CD
3. Add pre-commit to standardize the code

2023-04-20 00:19 UTC, xlurio requested changes
Welcome to the team! Good start you have there!

2023-04-20 00:19 UTC, xlurio commented on .github/workflows/test.yml
> +          poetry install
This probably won't be needed anymore since we are not going to use poetry for now hahah.
Poetry have an unstable and undocumented support for C extensions, which we are using for the last implemented feature. For that reason we are going to use `setuptools` for now, which not only have a good support for C extensions but is maintained by PyPA (Python Package Authority).
I'm sorry, I should have closed the issue but it didn't come into mind. We are going to hold this pull request until the next release and change the `poetry install` by `pip install .`

2023-04-20 00:19 UTC, xlurio commented on pyproject.toml
> +pre-commit = "^3.2.2"
I guess this should be in `[tool.poetry.group.dev.dependencies]` didn't it?

2023-04-20 13:02 UTC, RomuloGatto commented on pyproject.toml
> +pre-commit = "^3.2.2"
Yes, my mistake

2023-04-20 13:03 UTC, RomuloGatto commented on .github/workflows/test.yml
> +          poetry install
All good. Close the PR as you wish

2023-04-22 03:26 UTC, xlurio commented on .github/workflows/test.yml
> +          poetry install
The `main` branch is already using setuptools, be my guest to rebase your branch and make the changes needed!

2023-04-26 02:07 UTC, xlurio commented
Continued by https://github.com/verocloud/color-sorting-cli/pull/89

2023-04-26 02:07 UTC, closed without merging